services:
  backend:
    build: ./garage-backend
    container_name: garage-backend
    ports:
      - "5000:5000"
    networks:
      - garage-net
    depends_on:
      - plate-detector

  frontweb:
    build:
      context: ./frontweb
      args:
        REACT_APP_API_URL: https://garage-backend-rozt.onrender.com
    container_name: garage-frontweb
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - garage-net

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL: https://garage-backend-rozt.onrender.com
    container_name: garage-frontend
    ports:
      - "3001:80"
    depends_on:
      - backend
    networks:
      - garage-net

  plate-detector:
    build: ./plates
    container_name: plate-detector
    ports:
      - "3300:3300"
    networks:
      - garage-net
    command: ["python", "app.py"]

networks:
  garage-net:
