services:
  - type: web
    name: garage-backend
    env: docker
    plan: free
    rootDir: garage-backend

  - type: web
    name: garage-frontend
    env: docker
    plan: free
    rootDir: frontend

  - type: web
    name: garage-frontweb
    env: docker
    plan: free
    rootDir: frontweb

  - type: web
    name: plate-detector
    env: docker
    plan: free
    rootDir: plates
