services:
  - type: web
    name: garage-backend
    env: docker
    plan: free
    rootDir: garage-backend
    dockerfilePath: Dockerfile

  - type: web
    name: garage-frontweb
    env: docker
    plan: free
    rootDir: frontweb
    dockerfilePath: Dockerfile

  - type: web
    name: garage-frontend
    env: docker
    plan: free
    rootDir: frontend
    dockerfilePath: Dockerfile

  - type: web
    name: plate-detector
    env: docker
    plan: free
    rootDir: plates
    dockerfilePath: Dockerfile
